### ISSUE TITLE
[Bug]: `NEXTAUTH_URL` is set as prod URL on deploy preview 

### ISSUE THREAD

**Issue by colbyfayock** [netlify/next-runtime#1611]
### Summary

While trying to create a PR with Deploy Preview that includes Next.js, I noticed the `NEXTAUTH_URL` value was being overridden.

https://app.netlify.com/sites/50reactprojects/deploys/631aa4b96d37524db46b4ee1

```
10:28:50 PM: NextAuth package detected, setting NEXTAUTH_URL environment variable to https://50reactprojects.com/
```

I think I see 2 problems here:
* The value used is the prod domain, in this instance https://50reactprojects.com/ where the deploy is for a preview with a domain of https://deploy-preview-22--50reactprojects.netlify.app/
* I have `NEXTAUTH_URL` configured as a build environment variable and from what I understand, that should _not_ be overridden based on [what I'm seeing in the code](https://github.com/netlify/next-runtime/blob/e7bed15d6b7d2fd121b4cd6a3c9f1579b1ae90e3/packages/runtime/src/index.ts#L120)

### Steps to reproduce

1. Create a deploy preview where the production site does not have NextAuth.js installed, but the preview does
2. When the build/deploy runs, it sets NEXTAUTH_URL as the production site

### A link to a reproduction repository

https://github.com/colbyfayock/50reactprojects.com/pull/22

### Next Runtime version

4.21.3

### More information about your build

- [ ] I am building using the CLI
- [X] I am building using file-based configuration (`netlify.toml`)

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>

```toml
[build]
  publish = ".next"
  command = "yarn build"
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>

```toml
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>

```toml
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: false, // to prevent double entries
};

module.exports = nextConfig;
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

```
https://app.netlify.com/sites/50reactprojects/deploys/631aa4b96d37524db46b4ee1
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>

```
# Paste logs here
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>

```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by nickytonline** [comment]
Thanks for reporting this @colbyfayock! It should be all sorted now.

**Comment by kachar** [comment]
@nickytonline @colbyfayock 

Since the #1613 PR got merged we've got a regression on our Netlify account regarding NextAuth deployments. 
(Version [4.23.1](https://github.com/netlify/next-runtime/releases/tag/plugin-nextjs-v4.23.1) (2022-09-09))

We didn't set the environment var `NEXTAUTH_URL` manually (as the docs advise), so we ended up having the build redirecting users after login to https://develop--project-xxx-staging.netlify.app/login instead of our main custom domain URL (ex. https://app.project-xxx.com/login.

The custom domain is linked to our `develop` branch for automated deployments.

We've resolved the situation by manually setting the env var to our custom domain, however, we lose the ability to see and login to the preview builds if we want to use custom domains.

I guess we can enhance the functionality even further to use custom domains when they are set and if not to fall back to the deploy preview URLs.
