### ISSUE TITLE
Add redirects to onPreDev

### ISSUE THREAD

**Issue by sarahetter** [netlify/next-runtime#1633]
When adding 
```
[dev]
framework = "#static"
```
to the netlify.toml, `ntl dev` starts a static http server, serving files from the publish directory. This more closely mirrors what's happening with the app when it runs on Netlify. 

However, right now `ntl dev` fails and only displays "Not Found" on the page, as we haven't generated and added redirects to the netlify.toml file, as we're doing when actually building. We need to add these redirects in the onPreDev step to allow `ntl dev` to function properly in this case.

This is also blocking https://github.com/netlify/next-runtime/issues/1553

**Comment by ascorbic** [comment]
We'd not want this in the plugin though, because real users won't be setting `framework = #static` and it would stop `next dev` from working. What we really need is [a `next serve` command](https://github.com/netlify/cli/issues/3905), which would allow us to serve the site in an equivalent way to when deployed.

**Comment by orinokai** [comment]
I thought that was the purpose of `netlify dev`, to serve the site in an equivalent way to when deployed?

**Comment by sarahetter** [comment]
Closing as this isn't the way forward :)
