### ISSUE TITLE
Middleware matchers generate invalid Golang regexp capture groups

### ISSUE THREAD

**Issue by ascorbic** [netlify/next-runtime#1794]
We currently generate edge functions manifests with patterns generated from the middleware-manifest matcher regexp. The problem is that this now uses named capture groups, which have a different syntax in golang than JS.

In JS, a named capture group [has the form `(?<id> ...`](https://regex101.com/r/id6FsW/1) but Golang needs [the equivalent to be `(?P<id> ...`](https://regex101.com/r/7MRxN8/1). Right now when converting the JS pattern into Golang we just strip lookeaheads. It seems we may also need to convert these named capture groups too.

This is caught by the e2e test `edge-render-getserversideprops`, which gives a 500 error for `/123` as the edge function does not match, causing it to try to use a lambda, which has invalid syntax

The code is in here: https://github.com/netlify/next-runtime/blob/main/packages/runtime/src/helpers/matchers.ts

**Comment by orinokai** [comment]
@ascorbic i attempted this by doing a simple string replace at the same point we strip lookaheads and i have a draft PR here: https://github.com/netlify/next-runtime/pull/1809

However, it doesn't currently work because the edge-bundler tries to compile the pattern into a Regex object and thus gives an error: https://github.com/netlify/edge-bundler/blob/main/node/manifest.ts#L79

It doesn't seem necessary for the edge-bundler to compile these regex patterns, so I created an edge-bundler PR to simply use the patterns as strings: https://github.com/netlify/edge-bundler/pull/226

However, when doing so I realised that we might want to persue an alternative route, which would be to do the syntax transformation in the edge-bundler itself? Would be interested in your thoughts on it.
