### ISSUE TITLE
Middleware data redirects should normalize destination

### ISSUE THREAD

**Issue by ascorbic** [netlify/next-runtime#1800]
In middleware [we intercept redirects](https://github.com/netlify/next-runtime/blob/mk/all-the-tests/packages/runtime/src/templates/edge-shared/utils.ts#L163) inside data requests (i.e. those in `/_next/data/..`) and set the `x-next-redirect` header instead. This is because the router handles the redirect instead. However we're currently not normalizing the redirect target. The correct behaviour should be to always set it to the normalized path, even if the target is for the data URL. e.g. a redirect to `/_next/data/build-id/en-gb/hello.json?foo=bar` should be normalized to `/en-gb/hello?foo=bar`. Next.js implements this [here](https://github.com/vercel/next.js/blob/canary/packages/next/shared/lib/router/utils/get-next-pathname-info.ts#L46)

e2e test: `middleware-redirects`

**Comment by taty2010** [comment]
Looks like the files have changed since this was created. 

First link: https://github.com/netlify/next-runtime/blob/main/packages/runtime/src/templates/edge-shared/utils.ts#L250

Second link: https://github.com/vercel/next.js/blob/canary/packages/next/src/shared/lib/router/utils/get-next-pathname-info.ts#L46
