### ISSUE TITLE
[Bug]: Redirects are not working in the deployed application

### ISSUE THREAD

**Issue by lukasholzer** [netlify/next-runtime#1876]
### Summary

When I create a app with netlify and add a `_redirects` file and serve it with `ntl dev` it's working on the deployed app it's not

### Steps to reproduce

1. Clone this repo: https://github.com/lukasholzer/netlify-next-redirect-issue
2. Ntl dev (on the home page it should use the redirect)
3. Check out the deployed version (not working) https://main--euphonious-swan-75085e.netlify.app/

The site: https://app.netlify.com/sites/euphonious-swan-75085e/overview

### A link to a reproduction repository

https://github.com/lukasholzer/netlify-next-redirect-issue

### Next Runtime version

should be the latest in the CI

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

Mac OS

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>

```toml
# Paste content of your `netlify.toml` file here
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>

```toml
/       /foo
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>

```toml
# Paste content of your `next.config.js` file here. Check there is no private info in there.
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>

```
# Paste logs here
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>

```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by ascorbic** [comment]
This is your answer 😁  https://app.netlify.com/sites/euphonious-swan-75085e/deploys/63bd91ffe5d0c10009779bc0#L227

**Comment by lukasholzer** [comment]
oh my gosh I just should have read that! but I think it's still strange that it's working in `ntl dev` and not in prod (provides a wrong safety feeling)

**Comment by ascorbic** [comment]
Yeah, that has to be a bug. I wonder if dev is looking in the wrong publish dir

**Comment by scouttyg** [comment]
@lukasholzer @ascorbic One thing to note, the [docs](https://github.com/netlify/next-runtime/blob/main/docs/redirects-rewrites.md#using-_rewrites-and-_headers-files) mention that `_rewrites` and `_headers` should be moved to the `/public` folder, but it doesn't mention  `_redirects`. 

The docs could of course be updated to say that `_redirects` also need to be moved there, but as mentioned, that doesn't seem to then make things work in dev. 

Similarly, this I believe potentially conflicts with NextJS's `basePath` config option, as since anything in `public` is hoisted to the `basePath` defined folder, we can seemingly never do something like redirect the root path ("/") to the base path, so the preview urls of https://your-subdomain-here.netlify.app will 404, and we need to manually go to https://your-subdomain-here.netlify.app/your-base-path-here

**Comment by oskarhertzman** [comment]
how do you guys solve this?, can't see the logs

**Comment by serhalp** [comment]
@ascorbic Is this still valid for v5?
