### ISSUE TITLE
Overhaul our tests because our current scaffolding doesn't work with many of the new app-dir tests

### ISSUE THREAD

**Issue by nickytonline** [netlify/next-runtime#2161]
From @orinokai:

> we need to overhaul our tests because our current scaffolding doesn't work with many of the new app-dir tests - i think it's important to get a basic level of support shipped and then work on getting these tests in, but shout if you disagree

_Originally posted by @orinokai in https://github.com/netlify/next-runtime/pull/2080#discussion_r1228460598_

**Comment by orinokai** [comment]
Would very much like to overhaul our tests so that we can import the Next e2e tests verbatim, so they are easy to update for future versions. To do this, we'd need to develop a wrapper that can support this.

In addition, it's so important that the tests run faster and more reliably so I'd like to investigate how we could utilize `ntl serve` instead of actually deploying each site. This would involve bolstering `ntl serve` itself so it has greater parity with the production environment and will be easier to do if we can reduce our reliance on ODBs for ISR via the new cache-control primitives that are being discussed.

**Comment by orinokai** [comment]
further to the above, we also need to ensure we have a fast and reliable way to test our Runtime with previous versions of Next
